services:
  backend:
    image: dunglas/frankenphp:1-php8.4-alpine
    restart: unless-stopped
    ports:
      - "8000:80" # API will be at localhost:8000
      - "443:443"
    environment:
      SERVER_NAME: localhost, backend:80
      DATABASE_URL: "mysql://user:pass@db:3306/inspection_db?serverVersion=8.4.0&charset=utf8mb4"
    volumes:
      - ./backend:/app
      - caddy_data:/data
      - caddy_config:/config

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: inspection_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  caddy_data:
  caddy_config:
  db_data:
