# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: "%env(APP_SECRET)%"

    # Note that the session will be started ONLY if you read or write from it.
    session:
        handler_id: "snc_redis.session.handler"
        cookie_secure: false
        cookie_samesite: lax
        cookie_httponly: true
        cookie_lifetime: 0
        gc_maxlifetime: 604800

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
