nelmio_cors:
    defaults:
        allow_credentials: true
        origin_regex: false
        allow_origin: ["*"]
        allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
        allow_headers: ["Content-Type", "Authorization", "X-Requested-With"]
        expose_headers: ["Link"]
        max_age: 3600
    paths:
        "^/api":
            allow_origin: ["*"]
            allow_credentials: true
            allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
            allow_headers: ["Content-Type", "Authorization", "X-Requested-With"]
