app.swagger_json:
    path: /api/docs.json
    methods: [GET]
    controller: nelmio_api_doc.controller.swagger_json

app.swagger_ui:
    path: /api/docs
    methods: [GET]
    controller: nelmio_api_doc.controller.swagger_ui

# Override API Platform's documentation route
api_doc:
    path: /api/docs.{_format}
    methods: [GET, HEAD]
    controller: nelmio_api_doc.controller.swagger_ui
    requirements:
        _format: 'json|html'
